    steps:
      - uses: actions/checkout@v4
      - name: Build with Buildozer
        run: |
          yes | buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DUDE-APK
          path: bin/*.apk

