name: Build DUDE APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: EnisHaxhiaj/buildozer-action@v1
        with:
          command: buildozer android debug
